# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensysSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('censys', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='dnsrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arecords', models.CharField(max_length=500)),
                ('MXRecords', models.CharField(max_length=500)),
                ('SOARecords', models.CharField(max_length=500)),
                ('NameServer', models.CharField(max_length=500)),
                ('Records', models.CharField(max_length=500)),
                ('TXTRecords', models.CharField(max_length=500)),
                ('CNAME_Records', models.CharField(max_length=500)),
                ('AAAA_Records', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PageLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbdomain', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WappAlyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='whoisinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('Emails', models.CharField(max_length=500)),
                ('range', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WikiLeaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikileak', models.CharField(max_length=500)),
            ],
        ),
    ]
